baseurl: ""
url: ""

# Build
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "/page/:num"

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:title/

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed