baseurl: ""
url: "https://digitopia01.github.io"

# Build
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 12
paginate_path: "/page/:num"

# 신택스 하이라이터로 루즈를 선택함.
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:title/

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

google_analytics: "G-4T1D4KWX7L"
