title: Oinam Stories
email: hi@oinam.com
description: "Stories about kids, parenting, and fun things at Oinam."

url: ""
baseurl: ""

remote_theme: oinam/oinam-jekyll

username_twitter: oinam
username_instagram: oinam

markdown: kramdown
permalink: pretty
permalink: /:year/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - netlify.toml
  - README.*
  - vendor/
