title: Oinam Stories
description: Stories about kids, parenting, and fun things at Oinam.

remote_theme: oinam/oinam-jekyll

# Styles
styles:
  font_family: serif # serif, sans

markdown: kramdown
permalink: pretty
permalink: /:year/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - netlify.toml
  - README.*
  - vendor/