title: Oinam Stories
email: oinam@oinam.com
description: "Stories about kids, parenting, and fun things at Oinam."

baseurl: ""
url: "https://stories.oinam.com"

username_twitter: oinam
username_instagram: oinam

markdown: kramdown
permalink: pretty
permalink: /:title/

sass:
  style: :compressed

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Build settings
plugins:
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-feed

# jekyll-titles-from-headings, https://github.com/benbalter/jekyll-titles-from-headings/
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# optional-front-matter, https://github.com/benbalter/jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - netlify.toml
  - README.*
  - vendor/
