baseurl: ""
url: ""

# Build
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/archives/page/:num"

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:title/

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed