title: "Digitopia01"
logo: "/assets/image/headerlogo.png"
description: "digitopia01's engineering blog"
keywords: html, css, js, jquery, 개발공부, html공부, css공부, css속성, 개발자블로그, 깃허브블로그, 깃허브로개발블로그
color_scheme: auto # Options: auto (default), light, and dark

menu__settings:
  menu__items:
    - title: "HTML"
      target: ""
      url: "html"
    - title: "CSS"
      target: ""
      url: "css"
    - title: "JS"
      target: ""
      url: "js"

author:
  author__name: Digitopia01
  author__avatar: "/assets/image/headerlogo.png"
  author__bio: "digitopia01's engineering blog"

hero:
  hero__title: <span>welcome</span>, & greetings # <span></span> to highlight and underline text
  # hero__job: Photos, Videos, and Fairytales
  hero__description: "digitopia01's engineering blog"
  # hero__button__text: Read about my past
  # hero__button__link: '/about/'
  hero__image: "/assets/image/illustme.png"

# Footer Gallery
gallery:
  enable: true
  gallery__title: Gallery
  gallery__columns: "3" # gallery columns
  gallery__images:
    - image_url: "/assets/0/gallery/1.jpg"
    - image_url: "/assets/0/gallery/2.jpg"
    - image_url: "/assets/0/gallery/3.jpg"
    - image_url: "/assets/0/gallery/4.jpg"
    - image_url: "/assets/0/gallery/5.jpg"
    - image_url: "/assets/0/gallery/6.jpg"

# Social (via https://ionicons.com/v4/)
social:
  - { icon: "ion-logo-twitter", name: "Twitter", link: "https://twitter.com" }
  - {
      icon: "ion-logo-instagram",
      name: "Instagram",
      link: "https://www.instagram.com",
    }
  - {
      icon: "ion-logo-youtube",
      name: "Youtube",
      link: "https://www.youtube.com",
    }
  - { icon: "ion-logo-github", name: "Github", link: "https://github.com" }
  - {
      icon: "ion-logo-linkedin",
      name: "LinkedIn",
      link: "https://www.linkedin.com",
    }
