title: 'Oinam Stories'
# logo: '/assets/oinam-logotype.png'
description: 'Stories about kids, parenting, and fun things at Oinam.'
color_scheme: auto # Options: auto (default), light, and dark

menu__settings:
  menu__items:
    - title: 'Contact'
      target: '_blank'
      url: 'https://oinam.com/contact/'

author:
  author__name: Oinam
  author__avatar: '/assets/author-oinam.png'
  author__bio: 'Stories about kids, parenting, and fun things at Oinam.'

hero:
  hero__title: <span>fairy tales</span>, & fun # <span></span> to highlight and underline text
  # hero__job: Photos, Videos, and Fairytales
  hero__description: 'Stories about kids, parenting, and fun things at Oinam.'
  # hero__button__text: Read about my past
  # hero__button__link: '/about/'
  hero__image: '/assets/0/hero.jpg'


# Footer Gallery
gallery:
  enable: true
  gallery__title: Gallery
  gallery__columns: '3' # gallery columns
  gallery__images:
    - image_url: '/assets/0/gallery/1.jpg'
    - image_url: '/assets/0/gallery/2.jpg'
    - image_url: '/assets/0/gallery/3.jpg'
    - image_url: '/assets/0/gallery/4.jpg'
    - image_url: '/assets/0/gallery/5.jpg'
    - image_url: '/assets/0/gallery/6.jpg'

# Social (via https://ionicons.com/v4/)
social:
- {icon: 'ion-logo-twitter', name: 'Twitter', link: 'https://twitter.com/oinam/'}
- {icon: 'ion-logo-instagram', name: 'Instagram', link: 'https://www.instagram.com/oinam/'}
- {icon: "ion-logo-youtube", name: "Youtube", link: "https://www.youtube.com/@oinam/"}
- {icon: "ion-logo-github", name: "Github", link: "https://github.com/oinam/"}
- {icon: "ion-logo-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/company/oinam/"}